package com.frotty27.hrtk.api.mock;

import java.util.List;

/**
 * Captures UI commands generated by a {@code CustomUIPage} for assertion in tests.
 *
 * <p>Created via {@code UITestAdapter.buildPage(...)}. Records all UI commands
 * (SET, APPEND, REMOVE, etc.) issued against element paths, allowing tests to
 * verify that the UI layer produces the correct output.</p>
 *
 * <pre>{@code
 * UICommandCapture capture = adapter.buildPage(myPage);
 * myPage.update(data);
 * assertTrue(capture.hasCommand("hud.health.bar", "SET"));
 * assertTrue(capture.hasSet("hud.score.label", 42));
 * assertEquals(3, capture.getCount());
 * }</pre>
 *
 * @see com.frotty27.hrtk.api.assert_.UIAssert
 * @since 1.0.0
 */
public interface UICommandCapture {

    /**
     * Returns all captured UI command records in the order they were issued.
     *
     * @return an unmodifiable list of command records
     */
    List<UICommandRecord> getCommands();

    /**
     * Checks whether any captured command targets the given path with the given operation.
     *
     * @param path      the UI element path (selector)
     * @param operation the operation type (e.g., {@code "SET"}, {@code "APPEND"}, {@code "REMOVE"})
     * @return {@code true} if a matching command was found
     */
    boolean hasCommand(String path, String operation);

    /**
     * Checks whether any captured SET command targets the given path with the given value.
     *
     * @param path  the UI element path (selector)
     * @param value the expected value that was set
     * @return {@code true} if a matching SET command was found
     */
    boolean hasSet(String path, Object value);

    /**
     * Returns the number of UI commands captured so far.
     *
     * @return the command count
     */
    int getCount();

    /**
     * Represents a single captured UI command.
     *
     * @since 1.0.0
     */
    interface UICommandRecord {

        /**
         * Returns the UI element path this command targets.
         *
         * @return the element path (selector)
         */
        String getPath();

        /**
         * Returns the operation type of this command.
         *
         * @return the operation (e.g., {@code "SET"}, {@code "APPEND"}, {@code "REMOVE"})
         */
        String getOperation();

        /**
         * Returns the value associated with this command.
         *
         * @return the command value, or {@code null} if the operation has no value
         */
        Object getValue();
    }
}
